FROM redis
COPY redis.conf /usr/local/etc/redis/redis.conf
COPY startredis.sh /usr/local/bin/startredis.sh

# make the tmp dir accessible to the redis user who creates the socket
CMD [ "startredis.sh" ]