apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  replicas: 1
  selector:
    name: webserver
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
      - name: webserver
        image: docker.io/luebken/currentweather-go:0.0.2
        ports:
        - containerPort: 8080